


function test

%Reseting MATLAB environment
close all
clear all

addpath('Solar');
Error = 0;
Prop = 0;
i = 1;

%Import data
wscdata = Import_data();

%Declaring global variables
StopCounter = 2;
Stopped = 0;
index = 1;
playstat=0;
pausestat=0;
quitstat=0;
velocity = 60;
sliderval=1;
speedmultiplier=1;
looptime = 1;
disttravelled = 0;
capacity = 46.9;
voltage = 121.8;
SoC = 1;
solarPanelEf = 0.229; % 22.9% of effeciency
solarPanelArea = 4.0; % 4 meter squred
solarFluxScalingFactor = 0.75; % the atmosther will transmit a fraction (75%) of solar radiotion
SolarHelpers = SolarHelpersFunc;
Kp = 10; %72
Kd = 1000;
Ki = 0.001;
infoy = 0.85;
infox = 0.1;
wscroutey = 0.95;
wscroutex = 0.7;
timey = 0.85;
timex = 0.35;
batx = 0.01;
baty = 0.3;
%--------------------------------------------------------------
CurrentTime = datetime('now','TimeZone','Australia/Darwin','Format','HH:mm:ss');
CurrentTime.Year = 2017;
CurrentTime.Month = 10;
CurrentTime.Day = 10;
CurrentTime.Hour = 8;
CurrentTime.Minute = 00;
CurrentTime.Second = 00;

StopTime = CurrentTime;
StopTime.Hour = 17;
StartTime = CurrentTime;
SimTime = CurrentTime;
SimTime.Hour = 9;
StopStartTime = CurrentTime;
%--------------------------------------------------------------------

%Generating GUI
ScreenSize=get(0,'ScreenSize');

mainwindow=figure('Name','SolarProg',...
    'NumberTitle','Off',...
    'Menubar','none',...
    'Resize','off',...
    'Units','pixels',...
    'Position',[0,...
    0,...
    ScreenSize(3)-100,ScreenSize(4)-100],...
    'WindowKeyPressFcn',@pressfcn,...
    'DeleteFcn',@closegamefcn);

socfigure = axes('Parent',mainwindow,...
    'Units','normalized',...
    'Position',[0.2,0.12,0.35,0.35]);

speedslider=uicontrol('Parent',mainwindow,...
    'Style','slider',...
    'Value',1,...
    'Min',1,...
    'Max',1000,...
    'SliderStep',[1/999,2/999],...
    'Units','normalized',...
    'Position',[0.375,0.06,0.25,0.03],...
    'Callback',@movespeedsliderfcn);

speedtext=uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','1',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[0.475,0.03,0.05,0.03]);

startbutton=uicontrol('Parent',mainwindow,...
    'Style','pushbutton',...
    'String','Start Game',...
    'Visible','on',...
    'Units','normalized',...
    'Position',[0.01,0.01,0.2,0.05],...
    'Callback',@startgamefcn);

startdaybutton=uicontrol('Parent',mainwindow,...
    'Style','pushbutton',...
    'String','Start New Day',...
    'Visible','on',...
    'Units','normalized',...
    'Position',[0.41,0.01,0.2,0.05],...
    'Callback',@startgamefcn);

stopbutton= uicontrol('Parent',mainwindow,...
    'Style','pushbutton',...
    'String','Close Game',...
    'Units','normalized',...
    'Position',[0.79,0.01,0.2,0.05],...
    'Callback',@closegamefcn);


%---------------------TIME-------------------

timetext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','TIME',...
    'Units','normalized',...
    'Position',[timex,timey,0.1,0.04],'FontSize', 22);

timebox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','08:00',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[timex,timey-0.05,0.1,0.04],'FontSize', 22);


%------------------------------------------------
infotext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','INFO',...
    'Units','normalized',...
    'Position',[infox,infoy,0.15,0.04],'FontSize', 22);

solarpowertext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Solar Power',...
    'Units','normalized',...
    'Position',[infox-0.08,infoy-0.05,0.1,0.04],'FontSize', 18);

solarpowerbox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','121.8V',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[infox+0.05,infoy-0.04,0.03,0.02]);

powerconsumptiontext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Power Consumption',...
    'Units','normalized',...
    'Position',[infox-0.08,infoy-0.1,0.13,0.04],'FontSize', 18);

powerconsumptionbox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','46Ah',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[infox+0.05,infoy-0.09,0.03,0.02]);

velocitytext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Velocity',...
    'Units','normalized',...
    'Position',[infox-0.08,infoy-0.15,0.1,0.04],'FontSize', 18);

velocitybox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','65 km/h',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[infox+0.05,infoy-0.14,0.03,0.02]);

optimalvelocitytext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Optimal Velocity',...
    'Units','normalized',...
    'Position',[infox-0.08,infoy-0.2,0.1,0.04],'FontSize', 18);

optimalvelocity = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','65 km/h',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[infox+0.05,infoy-0.19,0.03,0.02]);
%-----------------------------------------------
wsctext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','WSC route',...
    'Units','normalized',...
    'Position',[wscroutex,wscroutey,0.15,0.04],'FontSize', 22);

wscmapbig = axes('Parent',mainwindow,...
    'Units','normalized',...
    'Position',[wscroutex-0.1,wscroutey-0.35,0.35,0.35]);

%  wscmappart = axes('Parent',mainwindow,...
%  'Units','normalized',...
%  'Position',[wscroutex-0.1,wscroutey-0.75,0.35,0.35]);
%-----------------------------------------

batterytext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Battery monitoring',...
    'Units','normalized',...
    'Position',[batx,baty,0.15,0.04],'FontSize', 22);

voltagetext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Voltage',...
    'Units','normalized',...
    'Position',[batx,baty-0.05,0.1,0.04],'FontSize', 18);

voltagebox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','121.8V',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[batx+0.09,baty-0.04,0.03,0.02]);

capacitytext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','Capacity',...
    'Units','normalized',...
    'Position',[batx,baty-0.1,0.1,0.04],'FontSize', 18);

capacitybox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','46Ah',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[batx+0.09,baty-0.09,0.03,0.02]);

SoCtext = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','SoC',...
    'Units','normalized',...
    'Position',[batx,baty-0.15,0.1,0.04],'FontSize', 18);

SoCbox = uicontrol('Parent',mainwindow,...
    'Style','text',...
    'String','100%',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.8,0.8,0.8],...
    'Units','normalized',...
    'Position',[batx+0.09,baty-0.14,0.03,0.02]);
%-------------------------------------------------------------------------------

%Inititiating graphics ----------------------------------------
    function pressfcn(~,event)
        switch event.Key
            
            case 'uparrow'
                velocity= velocity + 2;
            case 'downarrow'
                velocity= velocity - 2;
            case 'p'
                pausestat=1-pausestat;
        end
    end

    function closegamefcn(~,~)
        %Stopping game loop
        playstat=0;
        quitstat=1;
        pause(0.5)
        %Closing all windows
        delete(mainwindow)
    end

    function movespeedsliderfcn(~,~)
        sliderval=get(speedslider,'Value');
        sliderval=round(sliderval);
        set(speedtext,'String',num2str(sliderval))
    end

    function startgamefcn(~,~)
        %Locking user interface
        set(startbutton,'Visible','off')
        set(stopbutton,'Visible','on')
        playstat = 1;
        pausestat = 0;
   
        
        
%------------WRITE MAP------------------
        wscmapbig;
        h = worldmap('Australia');
        getm(h,'MapProjection');
        geoshow(wscmapbig,'landareas.shp', 'FaceColor', [0.15 0.5 0.15])
        geoshow(wscmapbig,'worldlakes.shp', 'FaceColor', 'cyan')
        geoshow(wscmapbig, wscdata(:,2),wscdata(:,1))
        hold on;
        StopIndex = find(wscdata(:,6));
        geoshow(wscmapbig,wscdata(StopIndex,2), wscdata(StopIndex,1), 'DisplayType', 'Point', 'Marker', 'O', 'Color', 'red');
        
%------------MAIN LOOP---------------
        
        while playstat == 1
            %Creating loop for game pause
            while pausestat
                pause(0.01)
                set(instructionbox,'String','Game paused!')
            end
            

           
        

            
            
            %-----------------CALCULATIONS-----------------------
         
            disttravelled = disttravelled + velocity(i)/3.6 * looptime;
            [avbSolarPower,collectedSolarPower] = SolarHelpers.CalculateSolarPowerInstantaneously(CurrentTime, wscdata(index,1),wscdata(index,2),solarPanelArea,solarPanelEf,1,solarFluxScalingFactor);
            
            Powerconsumption = Power_consumption(velocity(i),0);
            
            [ SoC, voltage, capacity ] = Battery_model(looptime, Powerconsumption - collectedSolarPower ,capacity);
            
            index = find_index(wscdata,3,disttravelled/1000);
            if (index >= StopIndex(StopCounter) && Stopped == 0)
                velocity(i+1) = 0;
                StopStartTime = CurrentTime;
                Stopped = 1;
                
            elseif (index >= StopIndex(StopCounter) && Stopped == 1)
                
                if floor((24 * 60 * datenum(CurrentTime)) - (24 * 60 * datenum(StopStartTime))) == 30  %% 24*60 is day to minute conversion 
                    index = index + 1;
                    Stopped = 0;
                    StopCounter = StopCounter + 1; 
                    velocity(i+1) = 60;
                else
                    velocity(i+1) = 0;
                end
               

            else
                
                
                   %----- PID--------
            SoC_ref = interp1([StartTime StopTime], [1 0.8],CurrentTime, 'linear');
            Error(i+1) = SoC_ref - SoC;
            Der(i+1)  = (Error(i+1) - Error(i))/looptime;
            Int(i+1)  = Error(i+1)*(looptime/2); % integration of the error
            I(i+1)    = sum(Int); % the sum of the integration of the error
            Prop(i+1) = Error(i+1);% error of proportional term 
            PID(i+1)  = Kp*Prop(i+1)+Ki*I(i+1)+ Kd*Der(i); % the three PID terms + Ki*I(i+1)+ Kd*Der(i) 
            velocity(i+1) = velocity(i) + (velocity(i)*PID(i+1)*-1);
            
                
            end
         
        
           %------------PLOT UI--------------------------
           set(powerconsumptionbox,'String',num2str(Powerconsumption));
           set(SoCbox,'String',num2str(SoC));
           set(voltagebox,'String',num2str(voltage));
           set(capacitybox,'String',num2str(capacity));
           set(velocitybox,'String',num2str(velocity(i)));
           plot(socfigure,[StartTime SimTime],[1 0.9777]);
           hold(socfigure);
           plot(socfigure,CurrentTime,SoC,'*');
           hold(socfigure);
           
            set(solarpowerbox,'String',num2str(collectedSolarPower)); 
            geoshow(wscmapbig,wscdata(index,2), wscdata(index,1), 'DisplayType', 'Point', 'Marker', '+', 'Color', 'red');
            
            CurrentTime.Second = CurrentTime.Second + looptime;
            set(timebox,'String',strcat(num2str(CurrentTime.Hour),':',num2str(CurrentTime.Minute),':',num2str(CurrentTime.Second)));

            pause(looptime/(speedmultiplier*sliderval))
            drawnow;
            i = i +1;
            %--------------------------------------------------
            
%             assignin('base','velocity',velocity);
          
        end
        
        
        %Unlocking user interface
        if quitstat==0
            set(startbutton,'Visible','on')
            set(stopbutton,'Visible','off')
            set(speedslider,'Enable','on')
        end
    end
%End of startgamefcn

end